from typing import Iterator, Generator, Any, Optional

class SSEClient:
    def __init__(self, event_source: Generator[bytes, None, None], **kwargs: Any) -> None: ...
    def events(self) -> Iterator[Event]: ...

class Event:
    @property
    def data(self) -> str: ...
    @property
    def event_type(self) -> Optional[str]: ...
    @property
    def last_event_id(self) -> Optional[str]: ...
    @property
    def retry(self) -> Optional[int]: ...
